#!/usr/bin/python3
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

fblist=[1,2]

while True:
    fb=(fblist[-1]+fblist[-2])
    if fb >= 4000000:
        break
    fblist.append(fb)

anwser = 0
for i in fblist:
    if i %2 == 0:
        anwser += i

print (anwser)

